name: check for new releases

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Build release checker
        run: ./gradlew clean build

      - name: Write output test
        run: java -jar build/libs/github-project-release-checker-0.1-all.jar https://github.com/signalapp/Signal-Desktop
        id: output_test
